### ISSUE TITLE
[Bug] Blocking MOTD URL

### ISSUE THREAD

**Issue by Bubka3** [PinionTech/Pinion-Adverts#28]
Blocking MOTD URL ''; must begin with 'http://' or 'https://' or be about:blank
Blocking MOTD URL ''; must begin with 'http://' or 'https://' or be about:blank
Blocking MOTD URL ''; must begin with 'http://' or 'https://' or be about:blank
Blocking MOTD URL ''; must begin with 'http://' or 'https://' or be about:blank
Blocking MOTD URL ''; must begin with 'http://' or 'https://' or be about:blank
Blocking MOTD URL ''; must begin with 'http://' or 'https://' or be about:blank
Blocking MOTD URL ''; must begin with 'http://' or 'https://' or be about:blank
Blocking MOTD URL ''; must begin with 'http://' or 'https://' or be about:blank
Blocking MOTD URL ''; must begin with 'http://' or 'https://' or be about:blank
Blocking MOTD URL ''; must begin with 'http://' or 'https://' or be about:blank
Blocking MOTD URL ''; must begin with 'http://' or 'https://' or be about:blank
Blocking MOTD URL ''; must begin with 'http://' or 'https://' or be about:blank
Blocking MOTD URL ''; must begin with 'http://' or 'https://' or be about:blank
Blocking MOTD URL ''; must begin with 'http://' or 'https://' or be about:blank
Blocking MOTD URL ''; must begin with 'http://' or 'https://' or be about:blank
Blocking MOTD URL ''; must begin with 'http://' or 'https://' or be about:blank
Blocking MOTD URL ''; must begin with 'http://' or 'https://' or be about:blank
Blocking MOTD URL ''; must begin with 'http://' or 'https://' or be about:blank
Blocking MOTD URL ''; must begin with 'http://' or 'https://' or be about:blank
Blocking MOTD URL ''; must begin with 'http://' or 'https://' or be about:blank
Blocking MOTD URL ''; must begin with 'http://' or 'https://' or be about:blank
Blocking MOTD URL ''; must begin with 'http://' or 'https://' or be about:blank
Blocking MOTD URL ''; must begin with 'http://' or 'https://' or be about:blank
Blocking MOTD URL ''; must begin with 'http://' or 'https://' or be about:blank
Blocking MOTD URL ''; must begin with 'http://' or 'https://' or be about:blank
Blocking MOTD URL ''; must begin with 'http://' or 'https://' or be about:blank
Blocking MOTD URL ''; must begin with 'http://' or 'https://' or be about:blank
Blocking MOTD URL ''; must begin with 'http://' or 'https://' or be about:blank
Blocking MOTD URL ''; must begin with 'http://' or 'https://' or be about:blank
Blocking MOTD URL ''; must begin with 'http://' or 'https://' or be about:blank
Blocking MOTD URL ''; must begin with 'http://' or 'https://' or be about:blank
Blocking MOTD URL ''; must begin with 'http://' or 'https://' or be about:blank
Blocking MOTD URL ''; must begin with 'http://' or 'https://' or be about:blank
Blocking MOTD URL ''; must begin with 'http://' or 'https://' or be about:blank
Blocking MOTD URL ''; must begin with 'http://' or 'https://' or be about:blank
Blocking MOTD URL ''; must begin with 'http://' or 'https://' or be about:blank
Blocking MOTD URL ''; must begin with 'http://' or 'https://' or be about:blank
Blocking MOTD URL ''; must begin with 'http://' or 'https://' or be about:blank
Blocking MOTD URL ''; must begin with 'http://' or 'https://' or be about:blank
Blocking MOTD URL ''; must begin with 'http://' or 'https://' or be about:blank
Blocking MOTD URL ''; must begin with 'http://' or 'https://' or be about:blank
Blocking MOTD URL ''; must begin with 'http://' or 'https://' or be about:blank
Blocking MOTD URL ''; must begin with 'http://' or 'https://' or be about:blank
Blocking MOTD URL ''; must begin with 'http://' or 'https://' or be about:blank

**Comment by SithSamurai** [comment]
This was resolved as best as possible quite a while ago. Any continued existence of this error message is due to a limitation imposed by the game engine.
